sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t 040772/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true 040772/react-test npm test

after_success: 
  - docker build -t 040772/multi-client ./client
  - docker build -t 040772/multi-nginx ./nginx
  - docker build -t 040772/multi-server ./server
  - docker build -t 040772/multi-worker ./worker

   # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
   # Take those images and push them to docker hub
  - docker push 040772/multi-client
  - docker push 040772/multi-nginx
  - docker push 040772/multi-server
  - docker push 040772/multi-worker

   # deploy to AWS     
deploy:
  provider: 'elasticbeanstalk'
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-248749481552'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY 
